-- Prayer-cell notification types. ADD VALUE is idempotent + safe on PG12+.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CELL_MEMBER_JOINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CELL_JOIN_REQUEST';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CELL_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CELL_SESSION_STARTED';
